spring.application.name=proiectPs

spring.datasource.url=jdbc:h2:~/mydatabase
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=org.h2.Driver

# Hibernate dialect for H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Automatically create/update the database schema based on your entities.
spring.jpa.hibernate.ddl-auto=update

# Enable the H2 console so you can view the database via a web browser (default path is /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Optional: Log SQL statements to the console
spring.jpa.show-sql=true

# JWT configuration
jwt.secret=your-very-secure-secret-key

spring.jmx.enabled=false

